In [1]:
import json
import numpy as np
import pandas as pd
import re

## Reward (premio)

In [2]:
ddf = pd.read_csv('premio_municipio.csv')             # cargar recompensas
ddf.drop(columns=['id', 'created_at'], inplace=True)  # quitar id y created_at
ddf

,experience,type,name,image
0,100,medal,medal = Aiora - València,https://appgchdaqxkcqudowisg.supabase.co/stora...
1,100,medal,medal = Albalat dels Sorells,https://appgchdaqxkcqudowisg.supabase.co/stora...
2,100,medal,medal = Alberic,https://appgchdaqxkcqudowisg.supabase.co/stora...
3,100,medal,medal = Alboraia,https://appgchdaqxkcqudowisg.supabase.co/stora...
4,100,medal,medal = Albors - València,https://appgchdaqxkcqudowisg.supabase.co/stora...
...,...,...,...,...
179,50,emblem,emblem = Torre del Virrey o de Babá_L'Eliana,https://appgchdaqxkcqudowisg.supabase.co/stora...
180,50,emblem,emblem = El Parc de la Pinada_L'Eliana,https://appgchdaqxkcqudowisg.supabase.co/stora...
181,50,emblem,emblem = Ayuntamiento de L'Eliana_L'Eliana,https://appgchdaqxkcqudowisg.supabase.co/stora...
182,50,emblem,emblem = Biblioteca Municipal_L'Eliana,https://appgchdaqxkcqudowisg.supabase.co/stora...
183,50,emblem,emblem = Poliesportiu_L'Eliana,https://appgchdaqxkcqudowisg.supabase.co/stora...

In [3]:
ddf.to_csv('rewardTown.csv', header=True, index=False)  # guardar csv

## Town (municipio)

In [4]:
tdf = pd.read_csv('municipio.csv')                      # cargar municipios
tdf.drop(columns=['uuid', 'created_at'], inplace=True)  # quitar uuid y created_at

rid = pd.read_csv('REWARD_rows.csv')                                   # cargar REWARD con los id asociados
rid = rid.drop(columns=['created_at', 'type', 'experience', 'image'])  # quitar columnas no necesarias

# quitar el tipo de recompensa delante del nombre en REWARD para que coincida con los nombres de TOWN
for i in range(len(rid)):
    rid.loc[i, 'name'] = re.sub('emblem = ', '', rid.loc[i, 'name'])
    rid.loc[i, 'name'] = re.sub('medal = ', '', rid.loc[i, 'name'])
    rid.loc[i, 'name'] = re.sub('_L\'Eliana', '', rid.loc[i, 'name'])

dctReward = rid.set_index('name')['id'].to_dict()  # crear diccionario con la correspondencia entre 'name' y 'id' (REWARD)
tdf['reward'] = tdf['name'].map(dctReward)         # actualizar 'reward' ('id' de REWARD) en TOWN

tdf

,name,province,address,latitude,longitude,reward
0,Aiora - València,València,València,39.466427,-0.342969,5a747717-6c77-44b4-89ce-f8928a890e36
1,Albors - València,València,València,39.451848,-0.374466,60684446-275c-4380-adff-0f258e55e8c9
2,Amistat - València,València,València,39.470333,-0.350394,5047f133-980c-40cc-baa4-a4e6bb577e39
3,Arrancapins - València,València,València,39.495679,-0.396211,15287d94-aefe-455d-b838-a535d37101b6
4,Benicalap - València,València,València,39.490028,-0.390928,bf5376e3-bc6d-4f09-ab7b-6de1b1b3ffd0
...,...,...,...,...,...,...
174,Xilxes,Castelló,"Plaza de España, 5",39.781208,-0.191755,cb7cd908-45f8-47ea-866b-5f9a43f3b295
175,Xirivella,València,"Plaza Concordia, 6",39.463949,-0.420941,ceb7c95c-9f79-43a2-ade1-9a24274d67c0
176,Xiva,València,"Plaza Gil Escarti, S/N",39.470644,-0.723284,dd614c45-25a9-4e40-ae8a-1d734ce66653
177,Xàtiva,València,"Alameda de Jaume I, 35",38.991833,-0.525374,2ca0ed4b-83db-4a3d-983d-7dd1edab9fce
178,Xèrica,Castelló,"Historiador Vayo, 19",39.915197,-0.569386,58b3ed39-61e3-4ddc-b1f1-e1a138e4f3fa

In [5]:
tdf.to_csv('town.csv', header=True, index=False)  # guardar csv

## Stop (parada)

In [6]:
sdf = pd.read_csv('Stop - Stop.csv')    # cargar paradas
sdf.drop(columns=['id'], inplace=True)  # quitar id

tid = pd.read_csv('TOWN_rows.csv')                                                                # cargar TOWN con los id asociados
tid = tid.drop(columns=['created_at', 'province', 'latitude', 'longitude', 'address', 'reward'])  # quitamos columnas no necesarias

sdf['id'] = np.nan                               # crear columna 'id'
dctTown = tid.set_index('name')['id'].to_dict()  # crear diccionario con la correspondencia entre 'name' y 'id' (TOWN)
sdf['id'] = sdf['town'].map(dctTown)             # actualizar 'id' en STOP

sdf.drop(columns=['town'], inplace=True)         # quitar 'town'
sdf.rename(columns={'id':'town'}, inplace=True)  # renombrar 'id' a 'town'

# hacemos lo mismo para reward
sdf['reward'] = sdf['name'].map(dctReward)        # actualizar 'reward' en STOP

sdf

,name,type,latitude,longitude,quizz,description,image,address,reward,town
0,Iglesia Parroquial de Ntra. Sra. del Carmen,Monumento,39.566670,-0.533330,NaN,El templo es de estilo neogótico y planta rect...,https://appgchdaqxkcqudowisg.supabase.co/stora...,"Calle Cristo del Consuelo, 8",26001881-3ee3-453d-b51c-88fdc9118446,9b66ea6d-f144-4e48-a251-1fa9f4232aed
1,Torre del Virrey o de Babá,Monumento,39.567555,-0.539345,NaN,La Torre del Virrey o Torre de Babà forma part...,https://appgchdaqxkcqudowisg.supabase.co/stora...,Calle València,f1a7c0da-e1a8-4a37-af6a-5d6e3b292eb8,9b66ea6d-f144-4e48-a251-1fa9f4232aed
2,El Parc de la Pinada,Parque,39.565162,-0.533541,NaN,"El parque, inaugurado en la década de los 90 d...",https://appgchdaqxkcqudowisg.supabase.co/stora...,Parque de La Pinada,25bf94ce-ad25-4110-a811-9d599499eed9,9b66ea6d-f144-4e48-a251-1fa9f4232aed
3,Ayuntamiento de L'Eliana,Edificios Gubernamentales,39.566581,-0.530186,NaN,Es en esta plaza donde empieza y termina la Sa...,https://appgchdaqxkcqudowisg.supabase.co/stora...,Plaza del País Valencia,f1dba120-4e1a-42f5-9668-a6cb4cef43c3,9b66ea6d-f144-4e48-a251-1fa9f4232aed
4,Biblioteca Municipal,Biblioteca,39.563645,-0.532434,NaN,Actualmente en obras,https://appgchdaqxkcqudowisg.supabase.co/stora...,"Calle General Pastor, 34,",ffa4d0fb-2084-4d67-a732-4ede38d8695f,9b66ea6d-f144-4e48-a251-1fa9f4232aed
5,Poliesportiu,Deportivo,39.572520,-0.529557,NaN,Múltiples deportes,https://appgchdaqxkcqudowisg.supabase.co/stora...,Avenida del Polideportivo,d107871f-9920-4839-af36-449a7498d28f,9b66ea6d-f144-4e48-a251-1fa9f4232aed

In [7]:
sdf.to_csv('stop.csv', header=True, index=False)  # guardar csv

## Station (estación)

In [8]:
gdf = pd.read_csv('transporte.csv')
gdf.drop(columns=['id'], inplace=True)

nan = gdf.index[gdf.isnull().any(axis=1)]  # miramos si hay faltantes

In [9]:
# localizamos faltantes
for i in nan:
    print(gdf.loc[i])

name              Valencia-La Font de Sant Lluis
line                                         NaN
geometry           POINT (-0.3660763 39.4411351)
longitude                              -0.366076
latitude                               39.441135
type                                       renfe
town         La Fonteta de Sant Lluís - València
Name: 1277, dtype: object
name                               El Puig
line                                   NaN
geometry     POINT (-0.3117602 39.5873418)
longitude                         -0.31176
latitude                         39.587342
type                                 renfe
town                               El Puig
Name: 1286, dtype: object
name                             El Romani
line                                   NaN
geometry     POINT (-0.3929023 39.3008731)
longitude                        -0.392902
latitude                         39.300873
type                                 renfe
town                               Sollana
Name: 1287, dtype: object
name                             L'Alcudia
line                                   NaN
geometry     POINT (-0.5866583 38.9692953)
longitude                        -0.586658
latitude                         38.969295
type                                 renfe
town                             L'Alcúdia
Name: 1291, dtype: object
name                    Nules-Villavieja
line                                 NaN
geometry     POINT (-0.152227 39.853502)
longitude                      -0.152227
latitude                       39.853502
type                               renfe
town                               Nules
Name: 1294, dtype: object
name                                Xativa
line                                   NaN
geometry     POINT (-0.5253742 38.9918333)
longitude                        -0.525374
latitude                         38.991833
type                                 renfe
town                                Xàtiva
Name: 1327, dtype: object

In [10]:
# sustituimos los faltantes por los valores correspondientes
gdf.loc[1277, 'line'] = 'C5,C6'
gdf.loc[1286, 'line'] = 'C5,C6'
gdf.loc[1287, 'line'] = 'C1'
gdf.loc[1291, 'line'] = 'C2'
gdf.loc[1294, 'line'] = 'C5'
gdf.loc[1327, 'line'] = 'C2'

In [11]:
# vemos que se hayan cambiado correctamente
for i in nan:
    print(gdf.loc[i])

name              Valencia-La Font de Sant Lluis
line                                       C5,C6
geometry           POINT (-0.3660763 39.4411351)
longitude                              -0.366076
latitude                               39.441135
type                                       renfe
town         La Fonteta de Sant Lluís - València
Name: 1277, dtype: object
name                               El Puig
line                                 C5,C6
geometry     POINT (-0.3117602 39.5873418)
longitude                         -0.31176
latitude                         39.587342
type                                 renfe
town                               El Puig
Name: 1286, dtype: object
name                             El Romani
line                                    C1
geometry     POINT (-0.3929023 39.3008731)
longitude                        -0.392902
latitude                         39.300873
type                                 renfe
town                               Sollana
Name: 1287, dtype: object
name                             L'Alcudia
line                                    C2
geometry     POINT (-0.5866583 38.9692953)
longitude                        -0.586658
latitude                         38.969295
type                                 renfe
town                             L'Alcúdia
Name: 1291, dtype: object
name                    Nules-Villavieja
line                                  C5
geometry     POINT (-0.152227 39.853502)
longitude                      -0.152227
latitude                       39.853502
type                               renfe
town                               Nules
Name: 1294, dtype: object
name                                Xativa
line                                    C2
geometry     POINT (-0.5253742 38.9918333)
longitude                        -0.525374
latitude                         38.991833
type                                 renfe
town                                Xàtiva
Name: 1327, dtype: object

In [12]:
# convertir tipo línea a json string
jsonl = {}
for l in gdf['line']:
    jsonl[l] = json.dumps(str(l).split(','))
    
# actualizar valor en el dataframe
gdf['line'] = gdf['line'].replace(jsonl)

gdf['id'] = np.nan                    # crear columna id
gdf['id'] = gdf['town'].map(dctTown)  # actualizar 'id' en STATION (usamos dctTown instanciado arriba)

gdf.drop(columns=['town'], inplace=True)         # quitar 'town'
gdf.rename(columns={'id':'town'}, inplace=True)  # renombrar 'id' a 'town'

gdf

,name,line,geometry,longitude,latitude,type,town
0,Mas del Rosari,"[""4""]",POINT (-0.435824990305418 39.52495960421599),-0.435825,39.524960,metrovalencia,111ac23f-44e6-4fc9-9bd6-047e8627b157
1,La Cova,"[""9""]",POINT (-0.4844444397042972 39.49888996240954),-0.484444,39.498890,metrovalencia,fd7eac02-8db6-457b-96fc-e1d7d72f9f08
2,Aeroport,"[""3"", ""5""]",POINT (-0.4749194388141947 39.49236683054559),-0.474919,39.492367,metrovalencia,fd7eac02-8db6-457b-96fc-e1d7d72f9f08
3,Almàssera,"[""3""]",POINT (-0.3542666730314796 39.512256661843445),-0.354267,39.512257,metrovalencia,b6f33b8b-7b41-4647-bf5c-404a66abf6c9
4,Colón,"[""3"", ""5"", ""7"", ""9""]",POINT (-0.3709277814305924 39.47014621855607),-0.370928,39.470146,metrovalencia,3a09d50e-feef-4067-bb93-eac1153c86c4
...,...,...,...,...,...,...,...
1324,Soneja,"[""C6""]",POINT (-0.4306676 39.8120247),-0.430668,39.812025,renfe,ed3b6743-168e-4968-b48b-8b6ef6b01528
1325,Vallada,"[""C2""]",POINT (-0.689953 38.908988),-0.689953,38.908988,renfe,c705ce1f-4173-45c9-8bb8-43bd267af9a6
1326,Venta Mina-Siete Aguas,"[""C3""]",POINT (-0.870661 39.454073),-0.870661,39.454073,renfe,ed0b29e9-b07c-4cd5-bf2f-73198b6a4e0a
1327,Xativa,"[""C2""]",POINT (-0.5253742 38.9918333),-0.525374,38.991833,renfe,f5178c29-5292-4047-8f0c-0e7f4293b90f
1328,Xirivella-L'Alter,"[""C4""]",POINT (-0.420941 39.4639487),-0.420941,39.463949,renfe,7fa30eef-75be-41d7-988d-3066c7fbe1c2

In [13]:
gdf.to_csv('station.csv', header=True, index=False)  # guardar csv