## Town

In [1]:
import pandas as pd

gdf = pd.read_csv('transporte.csv')
gdf

,id,name,line,geometry,longitude,latitude,type,town
0,237118.0,Mas del Rosari,4,POINT (-0.435824990305418 39.52495960421599),-0.435825,39.524960,metrovalencia,La Coma - València
1,237200.0,La Cova,9,POINT (-0.4844444397042972 39.49888996240954),-0.484444,39.498890,metrovalencia,Manises
2,237215.0,Aeroport,"3,5",POINT (-0.4749194388141947 39.49236683054559),-0.474919,39.492367,metrovalencia,Manises
3,237216.0,Almàssera,3,POINT (-0.3542666730314796 39.512256661843445),-0.354267,39.512257,metrovalencia,Almàssera
4,237142.0,Colón,"3,5,7,9",POINT (-0.3709277814305924 39.47014621855607),-0.370928,39.470146,metrovalencia,Sant Francesc - València
...,...,...,...,...,...,...,...,...
1324,67217.0,Soneja,C6,POINT (-0.4306676 39.8120247),-0.430668,39.812025,renfe,Soneja
1325,64004.0,Vallada,C2,POINT (-0.689953 38.908988),-0.689953,38.908988,renfe,Vallada
1326,66205.0,Venta Mina-Siete Aguas,C3,POINT (-0.870661 39.454073),-0.870661,39.454073,renfe,Venta Mina-Siete Aguas
1327,64100.0,Xativa,C2,POINT (-0.5253742 38.9918333),-0.525374,38.991833,renfe,Xativa
1328,69200.0,Xirivella-L'Alter,C4,POINT (-0.420941 39.4639487),-0.420941,39.463949,renfe,Xirivella-L'Alter

In [2]:
tdf = gdf.drop(columns=['id', 'name', 'line', 'geometry', 'longitude', 'latitude', 'type'])
tdf.rename(columns={'town':'name'}, inplace=True)
tdf.drop_duplicates(subset=['name'], inplace=True)
tdf.reset_index(drop=True, inplace=True)

In [3]:
# tdf.reindex(columns=['id']+tdf.columns.tolist()+['province', 'latitude', 'longitude', 'address', 'reward'])

In [4]:
tdf.to_csv('town.csv', header=True, index=False)

## Station

In [5]:
gdf.drop(columns=['id'], inplace=True)

In [6]:
import json

jsonl = {}
for l in gdf.line:
    jsonl[l] = json.dumps(str(l).split(','))

In [7]:
gdf['line'] = gdf['line'].replace(jsonl)

In [8]:
gdf

,name,line,geometry,longitude,latitude,type,town
0,Mas del Rosari,"[""4""]",POINT (-0.435824990305418 39.52495960421599),-0.435825,39.524960,metrovalencia,La Coma - València
1,La Cova,"[""9""]",POINT (-0.4844444397042972 39.49888996240954),-0.484444,39.498890,metrovalencia,Manises
2,Aeroport,"[""3"", ""5""]",POINT (-0.4749194388141947 39.49236683054559),-0.474919,39.492367,metrovalencia,Manises
3,Almàssera,"[""3""]",POINT (-0.3542666730314796 39.512256661843445),-0.354267,39.512257,metrovalencia,Almàssera
4,Colón,"[""3"", ""5"", ""7"", ""9""]",POINT (-0.3709277814305924 39.47014621855607),-0.370928,39.470146,metrovalencia,Sant Francesc - València
...,...,...,...,...,...,...,...
1324,Soneja,"[""C6""]",POINT (-0.4306676 39.8120247),-0.430668,39.812025,renfe,Soneja
1325,Vallada,"[""C2""]",POINT (-0.689953 38.908988),-0.689953,38.908988,renfe,Vallada
1326,Venta Mina-Siete Aguas,"[""C3""]",POINT (-0.870661 39.454073),-0.870661,39.454073,renfe,Venta Mina-Siete Aguas
1327,Xativa,"[""C2""]",POINT (-0.5253742 38.9918333),-0.525374,38.991833,renfe,Xativa
1328,Xirivella-L'Alter,"[""C4""]",POINT (-0.420941 39.4639487),-0.420941,39.463949,renfe,Xirivella-L'Alter

In [9]:
# gdf.to_csv('station.csv', header=True, index=False)

### Cambiar tipo town a _uuid_ (id)

In [10]:
tdf = pd.read_csv('TOWN_rows.csv')  # csv con los 'id' correspondientes a cada 'town'
tdf = tdf.drop(columns=['created_at', 'province', 'longitude', 'latitude', 'address', 'reward'])
tdf.rename(columns={'name':'town'}, inplace=True)
tdf

                                       id                      town
0    979d592a-1155-4138-98ca-8644de832d2a        La Coma - València
1    5d216f16-b82e-4cde-9cb3-610e92d59b6c                   Manises
2    3640e2a0-4c71-4273-b989-2b445bc10948                 Almàssera
3    8d5c90a8-cc41-4dd7-bbae-383467db38d7  Sant Francesc - València
4    fadfb503-0d57-4736-8724-1a0a6980a524          Ayora - València
..                                    ...                       ...
217  99f633f1-73f5-4acc-a7e0-9816c7ca74fc                    Soneja
218  b09cf60b-d96e-4588-b6c6-292b44bc053a                   Vallada
219  11cf998a-851b-488c-866a-e697b1dc7f43    Venta Mina-Siete Aguas
220  0e2f8e71-05a0-41b5-a23f-ba5d81af45cc                    Xativa
221  e726e730-a517-4995-ac65-b15e615d8526         Xirivella-L'Alter

[222 rows x 2 columns]

In [11]:
import numpy as np

gdf['id'] = np.nan                               # crear columna id
idMap = tdf.set_index('town')['id'].to_dict()    # crear diccionario con la correspondencia entre 'town' e 'id'
gdf['id'] = gdf['town'].map(idMap)               # actualizar 'id'
gdf.drop(columns=['town'], inplace=True)         # quitar 'town'
gdf.rename(columns={'id':'town'}, inplace=True)  # renombrar 'id' a 'town'
gdf

,name,line,geometry,longitude,latitude,type,town
0,Mas del Rosari,"[""4""]",POINT (-0.435824990305418 39.52495960421599),-0.435825,39.524960,metrovalencia,979d592a-1155-4138-98ca-8644de832d2a
1,La Cova,"[""9""]",POINT (-0.4844444397042972 39.49888996240954),-0.484444,39.498890,metrovalencia,5d216f16-b82e-4cde-9cb3-610e92d59b6c
2,Aeroport,"[""3"", ""5""]",POINT (-0.4749194388141947 39.49236683054559),-0.474919,39.492367,metrovalencia,5d216f16-b82e-4cde-9cb3-610e92d59b6c
3,Almàssera,"[""3""]",POINT (-0.3542666730314796 39.512256661843445),-0.354267,39.512257,metrovalencia,3640e2a0-4c71-4273-b989-2b445bc10948
4,Colón,"[""3"", ""5"", ""7"", ""9""]",POINT (-0.3709277814305924 39.47014621855607),-0.370928,39.470146,metrovalencia,8d5c90a8-cc41-4dd7-bbae-383467db38d7
...,...,...,...,...,...,...,...
1324,Soneja,"[""C6""]",POINT (-0.4306676 39.8120247),-0.430668,39.812025,renfe,99f633f1-73f5-4acc-a7e0-9816c7ca74fc
1325,Vallada,"[""C2""]",POINT (-0.689953 38.908988),-0.689953,38.908988,renfe,b09cf60b-d96e-4588-b6c6-292b44bc053a
1326,Venta Mina-Siete Aguas,"[""C3""]",POINT (-0.870661 39.454073),-0.870661,39.454073,renfe,11cf998a-851b-488c-866a-e697b1dc7f43
1327,Xativa,"[""C2""]",POINT (-0.5253742 38.9918333),-0.525374,38.991833,renfe,0e2f8e71-05a0-41b5-a23f-ba5d81af45cc
1328,Xirivella-L'Alter,"[""C4""]",POINT (-0.420941 39.4639487),-0.420941,39.463949,renfe,e726e730-a517-4995-ac65-b15e615d8526

In [12]:
gdf.to_csv('station.csv', header=True, index=False)